### ISSUE TITLE
setting up environment failed

### ISSUE THREAD

**Issue by saltsnack** [Abdullatif2/FL_Particpant_selection_Based_Fixed_and_dynamic_deadline#2]
Dear Mr,  I run the order"conda env create -f environment_partcipnat.yml", but it failed to solving environment.And the error information as below:
ResolvePackageNotFound: 
  - numexpr==2.7.1=py37hce01a72_0
  - libxslt==1.1.33=h33a18ac_0
  - ld64==274.2=1
......
  - pandas==1.0.1=py37h6c726b0_0
  - hdf5==1.10.4=hfa1e0ec_0
  - glib==2.63.1=hd977a24_0
I think there may be errors in the .yml file.Can you please  give me a hand? Thank you very much.

**Comment by Abdullatif2** [comment]
I checked the .yml file again and there were no errors. I don't know exactly why you are facing such a problem

**Comment by saltsnack** [comment]
Thank you for your answer.I'll try again.
